[mysql]
    addr = "127.0.0.1:3307"
    username = "root"
    password = "Bytecamp$21zu"
    database = "camp"
[redis]
    addr = "/var/run/redis/redis.sock"
#    addr = "180.184.74.13:6379"
    password = "21zu$Redis"
[rabbitMQ]
    addr = "127.0.0.1:5672"
    username = "guest"
    password = "guest"