[mysql]
    addr = "180.184.74.13:3306"
    username = "root"
    password = "bytedancecamp"
    database = "camp"
[redis]
    addr = "127.0.0.1:6379"
[rabbitMQ]
    addr = "180.184.74.13:5672"
    username = "guest"
    password = "guest"