[mysql]
    addr = "180.184.74.13:3306"
    username = "root"
    password = "Bytecamp$21zu"
    database = "camp"
[redis]
    addr = "180.184.74.13:6565"
    password = "21zu$Redis"
[rabbitMQ]
    addr = "180.184.74.13:5672"
    username = "guest"
    password = "guest"